name: WingVortex CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run build --if-present
    - uses: actions/upload-artifact@v1
      with:
        name: game-projectwingman
        path: dist/
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: game-projectwingman
        path: extension
    - name: Create Zip File
      uses: thedoctor0/zip-release@master
      with:
        filename: './game-projectwingman.zip'
        path: '.'
        directory: './extension'
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with: 
        body: |
          Download and install using the Extensions pane in Vortex.

          To manually install, extract the zip to %APPDATA%/Vortex/plugins/game-projectwingman.
        files: |
          ./extension/game-projectwingman.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  nexus:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore Tools
      shell: bash
      run: |
          dotnet tool install -g NexusUploader
    - name: Download build artifact
      uses: actions/download-artifact@v1
      with:
        name: game-projectwingman
        path: extension
    - name: Create Zip File
      uses: thedoctor0/zip-release@master
      with:
        filename: './game-projectwingman.zip'
        path: '.'
        directory: './extension'
    - name: Set version output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    - name: Validate unex config
      shell: bash
      run: |
        unex check -c
      env:
        UNEX_APIKEY: ${{ secrets.NEXUS_TOKEN }}
        UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
        UNEX_DEBUG: true
    - name: Run Nexus uploader
      shell: bash
      run: |
        unex upload 125 ./extension/game-projectwingman.zip -v ${{ steps.vars.outputs.tag }}
      env:
        UNEX_APIKEY: ${{ secrets.NEXUS_TOKEN }}
        UNEX_COOKIES: ${{ secrets.NEXUS_COOKIES }}
        UNEX_DEBUG: true